### ISSUE TITLE
parameter django model

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#124]
- class `Parameter`
- field "pk_model" -> Pharmacokinetic model (optional)
- field "pd_model" -> Pharmacodynamic model (optiona)
- field min value float
- field max value float
- field default value float
- field scale charoptions -> linear, log, sqrt
- constraint -> one of pk_model or pd_model must be set

**Comment by martinjrobins** [comment]
or Meta model Parameter, and concrete ones for pk and pd

**Comment by martinjrobins** [comment]
hi @xavierlave1, how far have you got on this? I've started on #165, which requires the database to store information on variable bounds, similar to what what is in this issue. I've made a draft of what I think it should look like in #166, which might help.

**Comment by xavierlave1** [comment]
@martinjrobins Actually I solved the parameters storing differently, as I stored them directly in the model's classes. (so there is no 'parameter' class for now, they are just a self parameter of each model).
I thought it was easier to use like this, because everything needed to work with the model would be centralised. 
What's your view on this ? Would you prefer a new class for each parameter ?

**Comment by martinjrobins** [comment]
What do you mean by "the model's classes", unfortunately the work model means many things! I just had a look at the `i124..` branch, and it looks like you are adding the parameter bounds into the dash app class in model_view.py? These bounds should be stored in the database so that the user can set parameter bounds for a model and have these persist, so they will need to be Django models (corresponding to a table in the database). Also, remember that the dash apps won't exist in the new version of the front-end, you should have  look at the `develop` branch.

**Comment by xavierlave1** [comment]
Yes that's what I was doing, didn't realise these would be gone in the new front-end. I will fork everything from the develop branch from now on, and store parameters as django models in the database

**Comment by xavierlave1** [comment]
Created the model in i124-save-parameters

**Comment by martinjrobins** [comment]
hi @xavierlave1, note that the class you have created in `i124-save-paramers` is a plain python class., but it should be a django model. Have a look at the docs here (https://docs.djangoproject.com/en/3.2/topics/db/models/), I've also created a draft of what this model should look like in the `pkpdapp/pkpdapp/models/variable.py` file in #166, so this would be useful to base your model on
