### ISSUE TITLE
Test css files

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#15]
Write test for the css files. Instructions for how to write tests for css are here

https://css-tricks.com/automatic-css-testing/
https://www.creativebloq.com/css3/4-tools-automatic-css-testing-7133777

It may be feasible to split the css file into smaller bits, but we have to check whether that is possible. So for example, split the main.css in multiple smaller css files and maybe combine them to form the main css, or import them all separately.

**Comment by martinjrobins** [comment]
using Material UI for frontend styling, we can use its styling
