### ISSUE TITLE
Inference structure

### ISSUE THREAD

**Issue by ben18785** [pkpdapp-team/pkpdapp#174]
This is a summary of the items discussed in regards to structure of inference in the app:

- Select dataset and model
  - User selects the dataset and model used for inference, from those within the current project 
- Controlling the number of parameters in the model:
  - This internally would be handled by the "inference model"
  - Externally, users would be able to select the parameters they want to estimate / fix parameters to certain values
- Noise models: users given a choice of
  - additive
  - multiplicative (which would be the default)
  - additive + multiplicative
  - Student t
- Which states are used for estimation?
  - Users would be able to specify within the app whether they want to use observations from all states or a subset of them to estimate parameters
  - user would link each state to a measurement in the dataset
- What priors would be used as default?
   - SBML files include "default" parameter values, which can be used to make "default" priors (perhaps along with the parameter bounds)
   - Each model, when uploaded from SBML, stores these default values and allows users to alter them, along with min/max bounds. This information is used to make the default priors
   - Users can also change priors as they see fit
- We may want to include, optimise, SAEM, "optimise then ML estimate" and Bayesian estimation in the app

Workflow:
1. User selects dataset and model
2. User selects parameters to perform inference on.
3. Default priors are presented to the user, these can be edited and changed according to user preferences
4. User selects one or more outputs of the model, and links each to a measurement in the dataset
5. When ready, user presses a button indicating to start the inference process
6. Back in the main screen, user is presented with a list of running/finished inference processes
7. Finished inference processes can be viewed (in some way yet to be determined....)

**Comment by martinjrobins** [comment]
Thanks @ben18785 , I've edit this with some of my thoughts, and added in a possible workflow

**Comment by ben18785** [comment]
Looks good! Thanks.

**Comment by ben18785** [comment]
Incorporating @KWang328's comment. Also been thinking about transformations and how to handle optimisation and sampling. Here's a potential idea for the workflow that would potentially avoid the user having to repeatedly select their parameters and data as they try different inference approaches. Note that, the user would probably not want to be faced with all these each time they do inference, so we'd need some way (e.g. with tabs) to make the various steps available without being necessary. 

# user creates an "inverse problem"
1. User selects dataset and model
2. User selects one or more outputs of the model and links each to a measurement in the dataset
3. User selects parameters to estimate
4. User names the inverse problem and gives it a description

# user creates an "inference problem": this is done after selecting a given inverse problem
1. User specifies their type of objective function: e.g. a score function, a log-likelihood or a log-posterior. Note this is not the user selecting their specific objective, which is done next
2. The user starts to build their objective function: for a score function, they select from a list; if a "log-likelihood" or "log-posterior" are selected in the previous step, they select a log-likelihood from a list
3. The known sigma Gaussian log-likelihood requires the user to specify sigma, so I guess this would need to be done here?
4. User determines whether to perform inference on the parameters or transformations of them (note that this will include any extra parameters for the log-likelihood that have been added)
5. Default parameter bounds are presented to the user based on their SBML file. Note, I'm still not sure how we handle this for Bayesian inference? As in, bounds in PINTS are only used for optimisation typically: do we need some method for creating truncated priors?
6. If the user is working with a log-posterior, default priors are presented to the user, which can be edited and changed according to user preferences
7. User names their inference problem or a default name is given, derived from their inverse problem + timestamp, perhaps?

# user creates an "inference method": done after selecting a inference problem
1. User selects whether to obtain point estimates or estimates with uncertainty. If their inference problem has a score function specified, they can only select point estimates
2. User presented with default methods for either optimisation or sampling but can change to another from a list
3. User selects how to initialise the search: the default initialisation is done based on the default parameter values and the bounds. But these can be changed and the initialisation approach specified: deterministic or random; if random, uniform or Gaussian. For deterministic, do we want a way of allowing a user to use a previous optimisation result as a start point?
4. User presented with default method options. Optimisation: number of start points, max number of function evaluations, sigma0; Sampling: number of chains, number of iterations, sigma0
5. User names their inference method

# user can then run their "inference method"
1. When ready, user presses a button indicating to start the inference process
2. Back in the main screen, user is presented with a list of running/finished inference processes. Finished inference processes can be viewed (in some way yet to be determined....)

Other things I'm not sure how to handle to make the workflow smoother:
- How can we make things nimbler if a user wants to change something? A good example is, suppose a user wants to fix a parameter that they've previously estimated. If they did this by hand, they would need to go back to the very beginning and create a new "inverse problem". But since PKPDApp only currently allows non-hierarchical parameters, the changes to the "inference problem" would be really minor: just removing the parameter (and any priors / boundaries) from the search space. Could we allow such deletions / additions of variables in a clever way that meant the user only needed to specify any new things that were necessary?

@KWang328 @martinjrobins @xavierlave1 let me know your thoughts.

**Comment by martinjrobins** [comment]
looks great @ben18785, thanks for putting it together. We can chat about it at the meeting, but I have a couple of comments:
1. does a "inverse problem" need to be separate from an "inference problem" can you run an inverse problem by itself?
2. "How can we make things nimbler if a user wants to change something" This is not a problem, and is why the model-view-controller concept is so much used in user interfaces. Think of the particular options selected for an "inference problem" as the "model", the "view" is the form that the user enters in their selection. So the action of viewing an inference problem presents you with the form, with all the previous options for that problem shown, and then you select whatever change you want to make and hit save or some other button.

**Comment by martinjrobins** [comment]
Also, I was thinking and I think it would be straightforward having a generalisation of multivariate + univariate priors. You could have an `InferenceVariable` django model, which would store
- type of prior (normal, uniform, ...others?)
- prior parameter one (sigma if normal, lower bound if uniform)
- prior parameter two (null if normal, upper bound if uniform)
- transformation type (might need parameters for this?)
- many-to-many relationship to zero or more `InferenceVariable`s. You can use a "through" table to store a sigma value, which is the covariate value between the two `InferenceVariable`s
- Foreign key relationship to an `InferenceProblem` that this variable belongs to

**Comment by ben18785** [comment]
Thanks @martinjrobins! Yes, I think you're right re: merging inverse problems and inference problems. I was originally thinking that keeping them separate would allow a user to chop and change more quickly but given what you've sent about my "nimble" question, this seems less important.

Re: priors, thanks. That's quite similar to what @xavierlave1 and I came up with and called a "Prior" model. I still don't quite see how you'd handled multivariate priors though: the prior parameters for such models won't be necessarily be specific to any one parameter. E.g. the multivariate normal covariance matrix. How would you store that sort of thing in this way?

**Comment by martinjrobins** [comment]
A many-to-many relationship between 2 tables is done using a third "through" table. Say you have three variables a, b & c, you want to store the following multivariate normal covariance matrix $sigma_xy$ with x in [a, b, c] and y in [a, b, c]. This translates into three different `InferenceVariables` one for each of a, b, and c. Each variable has a many-to-many relationship to three other variables, a, b and c, leading to 9 entries in this "through" table. Each entry in the "through" table also stores each element of $sigma_xy$

**Comment by ben18785** [comment]
That makes sense: thanks!

Suppose you had a hierarchical prior: theta_i ~ normal(mu, sigma) across lots of i. Would such a framework be able to handle that? Here it's not that the variables interrelate: rather that they relate to a higher level parameter.

**Comment by martinjrobins** [comment]
yea, I think you could probably fit the hierarchical stuff into a similar framework, each edge of your graph would be another many-to-many relationship. You would just have to make sure that the "through" table could handle each type of edge in the graph.... if that can be done..?

**Comment by martinjrobins** [comment]
I doubt its simpler :) But once you have a database schema that can represent your PPL, its easier to store and query, so it has that advantage over a PPL.
