### ISSUE TITLE
Test GUI / java scripts

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#20]
On the Django documentation it is suggest to test the entire app with selenium, see
https://docs.djangoproject.com/en/dev/topics/testing/tools/.

Maybe it is also possible / feasible to test the javascript or css script? Our would that contradict the principle of only testing what the user can see?

**Comment by martinjrobins** [comment]
we are using create-react-app for frontend, which incorporates Jest for testing
