### ISSUE TITLE
Upload data app

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#22]
import of data in a defined file format
- format: .csv
- column keys: ID of individual, time, measurements (possibly multiple columns), dose applied at that time point
- make sure that only feasible data sets are imported: not too large, other any other concerns?
- columns can be identified based on standardised column names or tagged by the user (time, concentration plus compartment, dose)
- tagging by user by clicking column heads and select from drop down menu
- each column comes with a unit tag. Again either read from the file in standardised way or tagged manually from a number of predefined units.
- which units do we need? (could just use myokit units for starters)
- display data in tabular form

**Comment by martinjrobins** [comment]
fyi @ben18785 , I've created a basic dataset create/update form in #86 if this is useful for this issue

**Comment by ben18785** [comment]
@martinjrobins thanks!
