### ISSUE TITLE
Use case for workflow 

### ISSUE THREAD

**Issue by KWang328** [pkpdapp-team/pkpdapp#245]
Dear Martin,
We planned two use cases for next week's sprint:
1. (3 compartment) PK model fitting to (naive pooled) data of one molecule tested with IV and Sc dosing with different dosing regimens
The model needs to be fitted simultaneously to all the data, i.e. fit IV and Sc data together (which means two slightly different model structures with shared parameters) and fit different regimen data together  
SBML file for the 3 compartment linear PK model already in the repository
Synthesized data: https://github.com/pkpdapp-team/pkpdapp-datafiles/tree/main/datasets/synthesized_pk_3comp

2. PKPD antibiotics (one compartment PK with adaptive resistant PD model) model fitting to (naive pooled) data of PK (plasma concentration) and PD (bacterial CFU time course), data obtained from different dose regimens need to be fitted simultaneously
One could fit PK first and then PD, or fit PKPD simultaneously
SBML file for the PD model already in the repository: https://github.com/pkpdapp-team/pkpdapp-datafiles/tree/main/models
Synthesized data: https://github.com/pkpdapp-team/pkpdapp-datafiles/tree/main/datasets/synthesized_antibio

**Comment by martinjrobins** [comment]
additional use case:
0. PK model fitting to (naive pooled) data of one molecule tested wtih a single dosing protocol

**Comment by KWang328** [comment]
Xavier has uploaded the updated data for the use case 0: 
https://github.com/pkpdapp-team/pkpdapp-datafiles/tree/main/datasets/Formatted_pk_3comp

**Comment by martinjrobins** [comment]
Notes from 2022/01/19 PKPD APP sprint 
Use case 0: 
-pick up initial condition for state variables from SBML file 
-pick up default parameter values from SBML file 
-Change size to volume  in the front end  (and associate the parameter name with the corresponding compartment) 
-Ka variable (rate from dose to central compartment) needs to be added 
-Dose compartment to be shown in the components 
-add in a data column route of administration (column header: ROUTE; IV direct dose into central compartment, the others need the dose compartment)
-change the initial values for inference to be sampled from prior
-jupyter notebook for data synthesis + optimization + MCMC  
-flat dose vs weight normalized 
-display the protocol in the front end 

Use case 1: 
- allow fitting multiple model simultaneously 
- identical parameters have the same name (if fitting simultaneously) 
- user interface to select individual data for fitting 

Use case 2: 
- Link PK and PD model automatically (user choose the link variables) 
- Guided PKPD workflow: Incorporating PK parameter uncertainty into PKPD inference

**Comment by martinjrobins** [comment]
closing as this was for the older version
