### ISSUE TITLE
Create minimal data upload app

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#25]
This is related #22 , but starts off with a narrower focus. 

Goals of this is PR:
   - Build a DataModel class which stores the data of the uploaded file
      - keys (for now): ID, TIME, MEASUREMENT (we can handle the exact data format in a separate PR)
   - This DataModel class integrates into the database using Djangos features
   - Create a function view that provides a user interface for uploading data 

This app should provide the interface to data importing anywhere in the PKPDApp.

**Comment by DavAug** [comment]
After some search it is suggested that the best way to store the data is either saving it as a file, or using a database that is specifically designed for time series data. 

See https://python.developreference.com/article/20213612/Django+%2B+Postgres+%2B+Large+Time+Series.

It may be easiest to start with storing the data as files, but we could have a look at the database option see #26 .

**Comment by martinjrobins** [comment]
it would be nice to use a time series database, but suspect files would be a lot easier...

**Comment by DavAug** [comment]
I realised that a minimal data upload app makes little sense, because data import is going to be used all over the place and before we don't have a proper solution I think it's better to keep models, forms, and views, with the app that is also processing the data. See #31 . I will therefore close this issue.
