### ISSUE TITLE
error 500 erros when uploading SBML file 

### ISSUE THREAD

**Issue by KWang328** [pkpdapp-team/pkpdapp#298]
when uplaoding this sbml file: 
https://raw.githubusercontent.com/pkpdapp-team/pkpdapp-datafiles/main/usecase2/ABx_updated3.xml
server error 500 occured

**Comment by martinjrobins** [comment]
I tried this one and it worked ok for me. Can you try again in a clean project and see if that works?

**Comment by martinjrobins** [comment]
fixed
