### ISSUE TITLE
Create AUCE app

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#31]
In this app we create a the AUCE workflow suggested by Antje and Ken. What the workflow should be able to do is to be able to 

- upload a file
- visualise that data as a scatter plot

The upload of the data is going to be a simple model form with a FileField for the data file, and a field for some summary statistics, such as id's, measured time interval, number of dosing regimens, etc. We can use these fields to check that the data has the format we are expecting. The file will then uploaded to some directory of the app, where we can access it for visualisation. This part will be replaced at a later stage by a time series data bank.

The visualisation then just accesses the file and plots it using plotly.

**Comment by martinjrobins** [comment]
done
