### ISSUE TITLE
user analytics - track logins

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#363]
need a way to track user logins to get an idea of how many people are using the app, and how much they are using the app

can django already do this?

**Comment by eatyourgreens** [comment]
[`django-user-visit`](https://www.fullstackpython.com/blog/track-daily-user-data-django-user-visit.html) looks like it might do this.

**Comment by eatyourgreens** [comment]
`django-user-visit` is installed on the development branch now, so development has a user visits table in the DB, and corresponding model, that we can interrogate for basic visitor stats.
