### ISSUE TITLE
Run tests of all Django apps in workflow

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#37]
At the moment the workflow only runs the tests of the pkpdapp and not its sub-apps like, explore_data. 

We can solve this either by using 
```
python pkpdapp/migrate.py test
```
and make sure that this tests all apps, or we write a routine ourselves that runs 
```
python pkpdapp/migrate.py test pkpdapp
python pkpdapp/migrate.py test explore_data
```
 and so on.

**Comment by martinjrobins** [comment]
I don't think this is relevent anymore?
