### ISSUE TITLE
user projects

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#39]
now that we have the ability to log-in, each user in the main pkpd app should have a list of projects that they are working on. There is a many-to-many relationship between users and projects.

Each user, while logged in, will have one currently active project, and everything that the user sees in the different apps (data analysis, simulation, inference etc) will depict the state of the currently active project. 

Eg. 
- you upload a data file while project A is active, that data file is associated with project A, and if you log back into the app and select project A, the data file will be already there. 
- If you perform an optimisation to get a set of likely parameter while project A is active, that optimisation result (parameters, associated data file and model) will be associated with project A, and be available to view whenever project A is active

The scope of this issue is to:
- create a project model and the many-to-many relationship
- add UI to be able to create a new project, see a list of previously created projects, and select the currently active project

**Comment by DavAug** [comment]
@martinjrobins 
That seems doable! I am guessing we at some places we just render the web interface personalised to the user?

Probably exceeding this ticket, but something I am not sure about is: how will we distribute computing resources once we have multiple users interacting with the app? Is this done automatically by the server?

**Comment by martinjrobins** [comment]
yes, that's right, each tab should be specific both to the user, and the currently active project.

re distributed computing resources, this is indeed the responsibility of the web server, so in general we don't have to worry about this. We will, however, have to worry about this for long-running simulations and inference algorithms.

**Comment by DavAug** [comment]
> yes, that's right, each tab should be specific both to the user, and the currently active project.
> 
> re distributed computing resources, this is indeed the responsibility of the web server, so in general we don't have to worry about this. We will, however, have to worry about this for long-running simulations and inference algorithms.

Ah ok thanks! That is what I was wondering.
