### ISSUE TITLE
Create NCA app

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#40]
Create a dashboard for the NCA computation

https://de.mathworks.com/help/simbio/ug/non-compartmental-analysis.html

A demo version is implemented in the branch i40-create-nca-app.

Tasks:
- Implement a class that can compute the NCA parameters
- Implement a the dashboard (potentially in a class)
- Handle states of the app with django-plotly-dash

**Comment by martinjrobins** [comment]
@Rebecca-Rumney and @DavAug, where is all the code for the NCA analysis?

**Comment by Rebecca-Rumney** [comment]
There's a basic form of the NCA in that branch which I started updating to be set up in a similar manner to the AUCE. However, the AUCE and datasets were still in development at that point so I moved over to doing the Myokit importing components and planned to return to this when they were implemented.

**Comment by martinjrobins** [comment]
ok cool. I can incorporate what is there to begin with.
