### ISSUE TITLE
Deploy AWS

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#48]
Heroku takes a long time to load the app.

After some browsing the reasons for this are probably
1. Heroku itself
2. potentially docker

Some suggestions were to use

https://aws.amazon.com/lambda/

to overcome these problems.

**Comment by martinjrobins** [comment]
I think the main reason for this is that we are not giving someone money! Moving up to the paid tiers on heroku would fix it, or hosting a vm/app on aws, azure or somewhere else.

**Comment by DavAug** [comment]
Yes potentially. I don’t really have much experience with this, but Benjamin from the new cohort suggested using AWS because they apparently give you 1000 clicks per months for free or something.

It seems that this would be enough for the initial phase of the app. What do you think? (I.e. faster loading times for free, as long as we don’t have more visitors than 1000 people per month)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martinjrobins** [comment]
yea, if its free why not ;) But you won't be able to use lambda for this, it's just used for isolated (lambda) functions rather than full web application backends
