### ISSUE TITLE
Django Models - Dataset, Model and Project

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#54]
Below is a draft of some of the models to be implemented into the app

## Timeseries Data Table
- dataset id (foreign key -> Dataset)
- row id (number - key)
- time (datetime)
- concentration (float)
- ...?  (is there one set of columns that cover all possible datasets, or do we need to be more flexible?)

## Dataset Table
- dataset id (key)
- description (text)
- ...?

## Model Table (do we need to split into PK, PD ?)
- model id (number)
- SBML (text field, or is there an xml field?)
- description (text)
- ...?

## Project 
- project id
- description (text)
- users (many-to-many relationship - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/)
- models (many-to-many to Model)
- datasets (many-to-many to Dataset)

**Comment by DavAug** [comment]
Hi good idea! Below I've added some suggestions to yours:

## Timeseries Data Table
- dataset id (foreign key -> Dataset)
- row id (number - key)
- time (datetime)
- biomaker (float)
- biomarker_id (number - key)
- biomarker unit (not sure whether we want this for every entry or only once per biomarker_id)
- dose (float)

(the number of PK and PD readouts may vary, so I'd suggest to have one biomarker column with an automatically generated key. The upload data format could still have the biomarker columns separately, but for storing things in the database, we need to fix the number of columns, and I believe that's a good way to fix it?)

## Dataset Table
- dataset id (key)
- description (text)
- type of administration (text)

## Model Table
- model id (number)
- model type (PK, PD) (I think we should label them for ease of model library interface?)
- SBML (text field)
- description (text)
- ...?

## Project 
- project id
- description (text)
- users (many-to-many relationship - https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/)
- models (many-to-many to Model)
- datasets (many-to-many to Dataset)

**Comment by martinjrobins** [comment]
Adding to david's biomarker type, we'd need a separate table for the possible biomarkers

## Biomarkers Table
biomarker_id (number - key)
unit (text - I think we'd keep this here, we probably want a standard unit for each biomarker?)
description (text)

**Comment by martinjrobins** [comment]
fixed in #86
