### ISSUE TITLE
create plot app

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#6]
May be split into smaller parts. One idea would be to use the django app

https://github.com/GibbsConsulting/django-plotly-dash

One example of what is possible with plotly dash is below:

https://dash-gallery.plotly.host/dash-svm/

Those to packages are however under MIT license, so need to check whether that is an issue.

**Comment by martinjrobins** [comment]
closing as part of the simulation tab placeholder
