### ISSUE TITLE
PDTimeSeriesPlot

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#68]
Implement a PDTimeSeriesPlot class to visualise one-dimensional pharmacodynamic time series.

- [ ] class that instantiates an empty go.Figure
- [ ] has show method to show the figure.
- [ ] has add_data method that adds a scatter trace of the PD time series. Takes a pandas.DataFrame with keys 'Time', 'Biomarker', 'Concentration'.
- [ ] Private method _set_layout that sets the layout. (plotly-white, size auto)

**Comment by martinjrobins** [comment]
swapping to javascript frontend
