### ISSUE TITLE
Django version for install

### ISSUE THREAD

**Issue by ben18785** [pkpdapp-team/pkpdapp#70]
I've been trying to install the app and am running into an issue about a Django version (in setup, I'm required to have Django version 3.0.7). I've tried to install this specific version with pip but I can't seem to get it. Of course, I can get a more recent version. Is there a particular reason for choosing this particular version or could we perhaps change this to (say)?

`Django>=3.0.7`

**Comment by prsndp** [comment]
Hey @ben18785, which Django version you want for your required app??

**Comment by martinjrobins** [comment]
think this is resolved now?
