### ISSUE TITLE
datasets and models for demo

### ISSUE THREAD

**Issue by martinjrobins** [pkpdapp-team/pkpdapp#80]

**Comment by KWang328** [comment]
Model: 
Compartment PK model (e.g. 2 compartment linear model overlaying with data)
Antibiotics in vitro PD and PKPD model (model code and data with Xavier)
Erlotinib model (data and model with David 
Selected CIT model

**Comment by ben18785** [comment]
In discussion, we think that having the csvs as demo files within the app is a good idea.
