### ISSUE TITLE
Splitting up AUCE dashboard

### ISSUE THREAD

**Issue by xavierlave1** [pkpdapp-team/pkpdapp#82]

**Comment by xavierlave1** [comment]
Splitting auce_dashboard.py into data_dashboard.py, data_selection.py and auce.py
Removing demo simulation tab in order to prepare for a more robust one

**Comment by martinjrobins** [comment]
hi @xavierlave1 and @DavAug. Where is the latest code for the AUCE dashboard? I can make a start incorporating it into the app if that is useful.
