### ISSUE TITLE
Create Contact form

### ISSUE THREAD

**Issue by DavAug** [pkpdapp-team/pkpdapp#9]
Contact should be made as easy as possible. Therefore there is a contact from at the bottom of the page. The form has to be properly connected so the submit sends an email to the developers.

**Comment by martinjrobins** [comment]
Is this already done @DavAug?

**Comment by DavAug** [comment]
Hi,
No, it’s really just the template that’s created. It’s not able to send any mails at the moment.

Sent from my iPhone

On 23 Sep 2020, at 06:13, Martin Robinson <notifications@github.com> wrote:

﻿

Is this already done @DavAug<https://github.com/DavAug>?
